<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ApplicationIcon>Assets\avalonia-logo.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Avalonia.Fonts.Inter" />

    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Include="Avalonia.Diagnostics">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>

    <PackageReference Include="Material.Avalonia" />
    <PackageReference Include="Material.Icons.Avalonia" />
    <PackageReference Include="Prism.Avalonia" />
    <PackageReference Include="Prism.DryIoc.Avalonia" />
    <PackageReference Include="Velopack" />
    <PackageReference Include="DialogHost.Avalonia" />
    <PackageReference Include="Material.Avalonia.DataGrid" />
    <PackageReference Include="Docnet.Core" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
    <None Update="Assets\app-icon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\avalonia-logo.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\avatar.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <AvaloniaXaml Remove="MainWindow.axaml" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="MainWindow.axaml.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ODProxl.ClientDtos\ODProxl.ClientDtos.csproj" />
    <ProjectReference Include="..\ODProxl.Utils\ODProxl.Utils.csproj" />
    <ProjectReference Include="..\ODProxl.ViewModels\ODProxl.ViewModels.csproj" />
  </ItemGroup>
</Project>
