<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Prism.Avalonia" />
		<PackageReference Include="Prism.DryIoc.Avalonia" />
		<PackageReference Include="Material.Icons.Avalonia" />
		<PackageReference Include="Prism.Avalonia" />
		<PackageReference Include="Prism.DryIoc.Avalonia" />
		<PackageReference Include="Docnet.Core" />
		<PackageReference Include="SkiaSharp" />
		<PackageReference Include="TreeDataGrid.Avalonia" />
		<PackageReference Include="WebDAVClient"/>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\ODProxl.ClientCommonModels\ODProxl.ClientCommonModels.csproj" />
		<ProjectReference Include="..\ODProxl.ClientDtos\ODProxl.ClientDtos.csproj" />
		<ProjectReference Include="..\ODProxl.ClientServices\ODProxl.ClientServices.csproj" />
		<ProjectReference Include="..\ODProxl.Global\ODProxl.Global.csproj" />
		<ProjectReference Include="..\ODProxl.TreeNodes\ODProxl.TreeNodes.csproj" />
		<ProjectReference Include="..\ODProxl.Utils\ODProxl.Utils.csproj" />
	</ItemGroup>
</Project>
